### PR TITLE
Claim debug

### PR DESCRIPTION
**Pull request by rista404**
I started writing deno for node a couple of hours ago, I have the first version working!
It's not compatible with browsers atm and the code is dirty, but I'll work on it more.

Missing functionality: extending debuggers, custom formatters, inspect opts, detecting color support, non-tty env. But looking good so far 😄 :

screen shot 2019-01-20 at 4 56 00 am

Any help or feedback is appreciated ✌️

### CODE REVIEW

**Comment by zhmushan** [comment]
One idea is that by having all the ported modules under one roof, we can attract more contributors.
Waiting for @kevinkassimo reply.

**Comment by kevinkassimo** [comment]
@zhmushan Can you clarify what you mean by "roof"?

**Review by kevinkassimo — APPROVED** [review]
LGTM. Thanks!

**Comment by zhmushan** [comment]
> @zhmushan Can you clarify what you mean by "roof"?

Like [deno_std](https://github.com/denoland/deno_std)

**Comment by kevinkassimo** [comment]
@zhmushan Hmm I think it is slightly different, since deno_std is basically maintained by Ryan, and libraries we are porting here are going to be maintained by each individuals. We could possibly set up a separate registry (than deno.land/x/) though.

**Comment by zhmushan** [comment]
@kevinkassimo 
I am more worried that some modules are updated in a nefarious way.
If moving to one repos (or the same organization), at least it must be reviewed by us, to a certain extent, it is reliable.

**Pull request merged**
